Shelter.destroy_all

  Shelter.create([
    {name: "Hong Kong Dog Rescue",
      address: "8 Shum Wan Road, Aberdeen",
      phone: "",
      website: "http://www.hongkongdogrescue.com/",
      donation_info: "http://www.hongkongdogrescue.com/donate/",
      description: "HKDR was founded in 2003 for the specific purpose of saving dogs and puppies from the Hong Kong Government’s Agriculture, Fisheries and Conservation Department (AFCD) Animal Management Centres, where around 10,000 dogs and puppies are destroyed every year. ",
      image: "http://www.hongkongdogrescue.com/wp-content/themes/theme46165-copy/images/logo.png",
      location: "hong kong",
      email: "hkdr@test.com",
      password: "12345678"
    },
    {name: "Society for the Prevention of Cruelty to Animals",
      address: "5 Wan Shing Street, Wan Chai",
      phone: "2802 0501",
      website: "www.spca.org.hk",
      donation_info: "http://www.spca.org.hk/en/join-us/make-a-donation",
      description: "Although we are the first charity in Hong Kong to deal with all aspects of animal welfare, we obtain around only 1% of our funding from the government. The rest of our funding comes from the generosity of the general public, for which we are extremely grateful. It is a constant challenge to raise the funds necessary to continue our work.",
      image: "https://hongkongvolunteer.files.wordpress.com/2013/07/spca_logo.jpg",
      location: "hong kong",
      email: "spca@test.com",
      password: "12345678"
    },
    {name: "Hong Kong Cats",
      address: "",
      phone: "51313921",
      website: "www.hongkongcats.org",
      donation_info: "http://hongkongcats.org/donate/",
      description: "Hong Kong Cats’ mission is to educate people about the importance of adopting animals, rather than buying them. We help place cats and kittens into loving homes, help injured Cats and Kittens.",
      image: "",
      location: "hong kong",
      email: "test2@test.com",
      password: "asdfasdf"
    },
    {name: "Hong Kong Alley Cat Watch",
      address: "",
      phone: "93100744",
      website: "http://www.hkalleycatwatch.com/contact.html",
      donation_info: "http://www.hkalleycatwatch.com/howdona.html",
      description: "HK Alley Cats Watch was founded in 1997. Privately funded, its sole aim was to help the plight of Hong Kong’s street cats.",
      image: "",
      location: "hong kong",
      email: "michelle@hkalleycatwatch.com",
      password: "12345678"
    }
  ])


Animal.destroy_all

Animal.create([
   {specie: "cat",
      color: "black and white",
      breed: "",
      age: nil,
      size: "small",
      sex: nil,
      name: "Bonnie",
      note: "",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'bonnie.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "cat",
      color: "black and white",
      breed: "",
      age: nil,
      size: "small",
      sex: nil,
      name: "Storm",
      note: "",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'storm.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "cat",
      color: "tabby and white",
      breed: "cat",
      age: "baby",
      size: "small",
      sex: "male",
      name: "Jacky",
      note: "My name is Jacky. I am a Tabby & White Male Domestic Short Hair and I was rescued from Cat Colony Care Programme.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'jacky.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "cat",
      color: "tabby",
      breed: "cat",
      age: "senior",
      size: "small",
      sex: "female",
      name: "Rendy",
      note: "My name is Rendy. I am a Tabby Female Domestic Long Hair(Spayed) and I was rescued by Inspectors.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'rendy.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "cat",
      color: "ginger and white",
      breed: "cat",
      age: "baby",
      size: "small",
      sex: "male",
      name: "Kimchi",
      note: "My name is Kimchi. I am a Ginger & White Male Domestic Short Hair and I was rescued by Inspectors.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'kimchi.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "reptile & fish",
      color: "",
      breed: "red eared slider terrapin",
      age: nil,
      size: "small",
      sex: nil,
      name: "Merry",
      note: "My name is Merry. I am a Green Unknown Red Eared Slider Terrapin and I was Abandoned by Owner.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'merry.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "reptile & fish",
      color: "",
      breed: "turtle",
      age: nil,
      size: "small",
      sex: nil,
      name: "Kai Kai",
      note: "My name is Kai Kai. I am a Green Unknown Turtle Other and I was Abandoned by Owner.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'kai_kai.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "reptile & fish",
      color: "",
      breed: "red eared slider terrapin",
      age: nil,
      size: "small",
      sex: nil,
      name: "Christmas",
      note: "My name is Christmas. I am a Green Unknown Red Eared Slider Terrapin and I was Abandoned by Owner.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'christmas.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "rodent",
      color: "grey",
      breed: "chinchilla",
      age: "adult",
      size: "small",
      sex: "male",
      name: "Jay",
      note: "My name is Jay . I am a Grey Male Chinchilla and I was Abandoned by Owner.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'jay.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "rodent",
      color: "white",
      breed: "guinea pig",
      age: "baby",
      size: "small",
      sex: "male",
      name: "Makie",
      note: "My name is Makie. I am a White Female Guinea Pig and I was rescued from Other Shelter.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'makie.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "rabbit",
      color: "white",
      breed: "domestic",
      age: "young",
      size: "small",
      sex: "male",
      name: "Tommy",
      note: "My name is Tommy. I am a White Male Domestic(Desexed) and I was Abandoned by Owner.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'tommy.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "dog",
      color: "tan and black",
      breed: "multibreed",
      age: "young",
      size: "medium",
      sex: "female",
      name: "Olive",
      note: "Olive was quite shy when she was younger but she has grown in confidence over the months and is now a very sweet and loving girl. You can meet her any Sunday at Whiskers N Paws, or any other day by arrangement. ",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Olive.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "dog",
      color: "tan and white",
      breed: "Jack Russell",
      age: "senior",
      size: "small",
      sex: "male",
      name: "Jerry",
      note: "",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Jerry.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "dog",
      color: "white",
      breed: "Pomeranian",
      age: "adult",
      size: "small",
      sex: "male",
      name: "Panda",
      note: "",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Panda.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "dog",
      color: "black",
      breed: "multibreed",
      age: "baby",
      size: "large",
      sex: "female",
      name: "Raven",
      note: "Raven is a beautiful young girl with a glossy all black coat. Not only does she have gorgeous looks, but also a sweet personality. She easily fits in with other dogs and is really happy to be with people and loves going out for walks. Raven is a ball of energy and can't stop jumping around with joy. She would need a home where she can get lots of exercise to expend all her energy. Raven loves playing fetch with any toys she can get.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Raven.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "dog",
      color: "ginger",
      breed: "multibreed",
      age: "young",
      size: "large",
      sex: "male",
      name: "Roofie",
      note: "Roofie is a very relaxed and sweet natured boy. He has such a gentle disposition and is always quiet and calm. He gets along very well with other dogs and people. He is very polite, asking nicely for pats and is in no way demanding. He is toilet trained and loves going for walks and spending time with people. Roofie is small to medium sized making him perfect for HK apartment living. Please come meet this gentle guy in Tai Po! ",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Roofie.jpg')}"),
      shelter_id: Shelter.first.id
    },
    {specie: "cat",
      color: "ginger and white",
      breed: "domestic",
      age: nil,
      size: "small",
      sex: "female",
      name: "Bella",
      note: "Gorgeous ginger girl Bella loves talking – but she loves being scratched under her chin even more; just start rubbing her there and the talking stops, replaced by super-loud purring! And apart from being a total lovebug, she also loves watching TV... especially wildlife documentaries (she has a particular interest in groundhogs!).",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Bella.JPG')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "cat",
      color: "black and white",
      breed: "",
      age: "young",
      size: "small",
      sex: "female",
      name: "MeiMei",
      note: "Mei Mei is three years old. Her name means ‘Beautiful Tail’ in Chinese. She was separated from her mum and siblings as a kitten and rescued from a condemned building. She loves to be petted and is very smart, responding to her name when called. Mei Mei should get along well with other cats as she is quite submissive. She is a beautiful cat with a sweet temperament. However, she doesn’t like to be held and is very shy until she is familiar with her environment. Mei Mei needs her own forever family! Can you help?",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'Meiimei.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "cat",
      color: "ginger",
      breed: "",
      age: "unknown",
      size: "small",
      sex: "male",
      name: "Bruce",
      note: "Bruce is looking for new home. He was rescued from a storm drain in Shek O and hand-reared after being separated from his mother during a storm when he was only a day old. This 2 year old healthy, handsome guy is an affectionate, playful lap cat that needs a bit of attention and love each day. Sadly he can sometimes be a little too playful for our small children and their friends and he’s looking for a child-free home where he can have some quiet and an owner who is able to pet him and play with him. He was raised with dogs during his early weeks, so should be okay in a dog-friendly household. ",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'bruce.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "dog",
      color: "chocolate",
      breed: "mongrel",
      age: "unknown",
      size: "large",
      sex: "male",
      name: "thomas",
      note: "My name is Thomas. I am a Chocolate Male Mongrel(Neutered) and I was rescued from a prosecution case.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'thomas.jpg')}"),
      shelter_id: Shelter.last.id
    },
    {specie: "dog",
      color: "black & brindle",
      breed: "mongrel",
      age: "unknown",
      size: "large",
      sex: "female",
      name: "samiya",
      note: "Samiya is a black and brindle colored mixed breed puppy girl. Sweet and passionate. She loves to interact with people and like to be reward with pat. She is looking for someone likes to teach her all good manners to be calm and polite.",
      avatar: File.open("#{Rails.root.join('app', 'assets', 'images', 'samiya.jpg')}"),
      shelter_id: Shelter.last.id
    }
  ])